/// Dimensao do desfecho clinico do atendimento.
table dDesfecho
	lineageTag: ef22f964-ecf4-4cc9-9fcd-b9db2ad1dbaa

	/// Resultado registrado ao fim do atendimento
	column Desfecho
		dataType: string
		isKey
		lineageTag: 1c2d52e4-6f2b-48ca-bafc-f8ab1941e660
		summarizeBy: none
		sourceColumn: Desfecho
		sortByColumn: Ordem

		annotation SummarizationSetBy = Automatic

	/// Ordem de exibicao, do melhor ao pior desfecho
	column Ordem
		dataType: int64
		formatString: 0
		lineageTag: 837a83a5-96aa-4969-bcb4-1306922bc955
		summarizeBy: none
		sourceColumn: Ordem

		annotation SummarizationSetBy = Automatic

	/// Vale 1 quando o desfecho e obito; usado na taxa de mortalidade
	column Obito_Flag
		dataType: int64
		formatString: 0
		lineageTag: 806e64c9-4d6d-483f-835c-6c3a836d000e
		summarizeBy: sum
		sourceColumn: Obito_Flag

		annotation SummarizationSetBy = Automatic

	/// Separa desfechos resolutivos dos que exigem continuidade
	column Favoravel
		dataType: string
		lineageTag: 3142935b-a66a-49ae-bea9-f2a1697aa51d
		summarizeBy: none
		sourceColumn: Favoravel

		annotation SummarizationSetBy = Automatic

	partition dDesfecho = m
		mode: import
		queryGroup: Dimensoes
		source =
				let
				    Unicos = Table.Distinct( Table.SelectColumns( Fonte, {"Desfecho"} ) ),
				    ComOrdem = Table.AddColumn( Unicos, "Ordem", each
				        if [Desfecho] = "Alta" then 1
				        else if [Desfecho] = "Retorno agendado" then 2
				        else if [Desfecho] = "Transferência" then 3 else 4, Int64.Type ),
				    ComObito = Table.AddColumn( ComOrdem, "Obito_Flag", each
				        if [Desfecho] = "Óbito" then 1 else 0, Int64.Type ),
				    ComFavoravel = Table.AddColumn( ComObito, "Favoravel", each
				        if [Desfecho] = "Alta" then "Resolvido" else "Exige continuidade", type text ),
				    Ordenado = Table.Sort( ComFavoravel, {{"Ordem", Order.Ascending}} )
				in
				    Ordenado

	annotation PBI_ResultType = Table
