/// Dimensao que separa atendimentos com e sem internacao.
table dInternacao
	lineageTag: 0f36515c-9474-4a0f-a656-1604d8c85dad

	/// Sim ou Nao
	column Internacao
		dataType: string
		isKey
		lineageTag: 89275551-5842-4070-ab1d-0d32c389a382
		summarizeBy: none
		sourceColumn: Internacao
		sortByColumn: Ordem

		annotation SummarizationSetBy = Automatic

	/// Ordem de exibicao
	column Ordem
		dataType: int64
		formatString: 0
		lineageTag: 8df8246d-f654-40b8-8eeb-b74a605bf786
		summarizeBy: none
		sourceColumn: Ordem

		annotation SummarizationSetBy = Automatic

	/// Vale 1 quando houve internacao; usado na taxa de internacao
	column Internacao_Flag
		dataType: int64
		formatString: 0
		lineageTag: 2769d1b6-8e03-4df1-8394-cc1a44198261
		summarizeBy: sum
		sourceColumn: Internacao_Flag

		annotation SummarizationSetBy = Automatic

	partition dInternacao = m
		mode: import
		queryGroup: Dimensoes
		source =
				let
				    Unicos = Table.Distinct( Table.SelectColumns( Fonte, {"Internacao"} ) ),
				    ComOrdem = Table.AddColumn( Unicos, "Ordem", each if [Internacao] = "Não" then 1 else 2, Int64.Type ),
				    ComFlag = Table.AddColumn( ComOrdem, "Internacao_Flag", each if [Internacao] = "Sim" then 1 else 0, Int64.Type ),
				    Ordenado = Table.Sort( ComFlag, {{"Ordem", Order.Ascending}} )
				in
				    Ordenado

	annotation PBI_ResultType = Table
