/// Dimensao do perfil demografico do paciente: sexo cruzado com faixa etaria.
table dPaciente
	lineageTag: 1ba224d4-a648-4b92-becf-d17ac63e1d43

	/// Chave do perfil: sexo e faixa etaria concatenados
	column Perfil
		dataType: string
		isKey
		lineageTag: aa0b1c2a-b629-4e9e-8091-204d51b0d9fb
		summarizeBy: none
		sourceColumn: Perfil

		annotation SummarizationSetBy = Automatic

	/// Sexo declarado
	column Sexo
		dataType: string
		lineageTag: 48db400e-1670-427b-a533-d77313aa2145
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	/// Faixa etaria do paciente
	column Faixa_Etaria
		dataType: string
		lineageTag: c12a1785-4118-4624-b072-f605701990e4
		summarizeBy: none
		sourceColumn: Faixa_Etaria
		sortByColumn: Faixa_Ordem

		annotation SummarizationSetBy = Automatic

	/// Ordem crescente das faixas etarias
	column Faixa_Ordem
		dataType: int64
		formatString: 0
		lineageTag: 4717e687-6f86-4277-8859-cd23c4d8426d
		summarizeBy: none
		sourceColumn: Faixa_Ordem

		annotation SummarizationSetBy = Automatic

	/// Agrupa as faixas em crianca, adulto e idoso
	column Geracao
		dataType: string
		lineageTag: 52ef0c9f-0dcc-488b-8abc-7a0a078bf5d9
		summarizeBy: none
		sourceColumn: Geracao

		annotation SummarizationSetBy = Automatic

	partition dPaciente = m
		mode: import
		queryGroup: Dimensoes
		source =
				let
				    Unicos = Table.Distinct( Table.SelectColumns( Fonte, {"Perfil_Paciente","Sexo","Faixa_Etaria"} ), {"Perfil_Paciente"} ),
				    Renomeado = Table.RenameColumns( Unicos, {{"Perfil_Paciente","Perfil"}} ),
				    ComOrdem = Table.AddColumn( Renomeado, "Faixa_Ordem", each
				        if [Faixa_Etaria] = "0-12" then 1
				        else if [Faixa_Etaria] = "13-17" then 2
				        else if [Faixa_Etaria] = "18-29" then 3
				        else if [Faixa_Etaria] = "30-44" then 4
				        else if [Faixa_Etaria] = "45-59" then 5 else 6, Int64.Type ),
				    ComGeracao = Table.AddColumn( ComOrdem, "Geracao", each
				        if [Faixa_Ordem] <= 2 then "Crianca e adolescente"
				        else if [Faixa_Ordem] <= 5 then "Adulto" else "Idoso", type text ),
				    Ordenado = Table.Sort( ComGeracao, {{"Faixa_Ordem", Order.Ascending}, {"Sexo", Order.Ascending}} )
				in
				    Ordenado

	annotation PBI_ResultType = Table
