/// Dimensao do carater do atendimento: eletivo, urgencia ou emergencia.
table dTipoAtendimento
	lineageTag: 88692aa0-655e-4efb-aca6-0a207abcc217

	/// Eletivo, Urgencia ou Emergencia
	column Tipo
		dataType: string
		isKey
		lineageTag: d733c1c1-fd21-405d-a36f-78a92c983863
		summarizeBy: none
		sourceColumn: Tipo
		sortByColumn: Ordem

		annotation SummarizationSetBy = Automatic

	/// Ordem de exibicao, do menos ao mais grave
	column Ordem
		dataType: int64
		formatString: 0
		lineageTag: b31aa8e5-32f8-4d5e-8042-92f8521b4675
		summarizeBy: none
		sourceColumn: Ordem

		annotation SummarizationSetBy = Automatic

	/// Separa o que e programado do que chega sem agendamento
	column Carater
		dataType: string
		lineageTag: e0253b7b-884c-408a-a769-635c9c9e442c
		summarizeBy: none
		sourceColumn: Carater

		annotation SummarizationSetBy = Automatic

	partition dTipoAtendimento = m
		mode: import
		queryGroup: Dimensoes
		source =
				let
				    Unicos = Table.Distinct( Table.SelectColumns( Fonte, {"Tipo_Atendimento"} ) ),
				    Renomeado = Table.RenameColumns( Unicos, {{"Tipo_Atendimento","Tipo"}} ),
				    ComOrdem = Table.AddColumn( Renomeado, "Ordem", each
				        if [Tipo] = "Eletivo" then 1 else if [Tipo] = "Urgência" then 2 else 3, Int64.Type ),
				    ComCarater = Table.AddColumn( ComOrdem, "Carater", each
				        if [Tipo] = "Eletivo" then "Programado" else "Nao programado", type text ),
				    Ordenado = Table.Sort( ComCarater, {{"Ordem", Order.Ascending}} )
				in
				    Ordenado

	annotation PBI_ResultType = Table
