/// Dimensão de aeroportos da malha, com localização geográfica.
table dAeroporto
	lineageTag: 90efbe19-3fc7-4727-b766-bbd9b6178b40

	/// Código IATA de três letras
	column 'IATA'
		dataType: string
		lineageTag: 36fc1b0a-6a76-489c-be0b-f0371c2a1a0d
		summarizeBy: none
		sourceColumn: IATA
		isKey

		annotation SummarizationSetBy = Automatic

	/// Rótulo no formato Cidade (IATA)
	column 'Aeroporto'
		dataType: string
		lineageTag: 5810d504-609a-4358-a541-bd1716558176
		summarizeBy: none
		sourceColumn: Aeroporto

		annotation SummarizationSetBy = Automatic

	/// Cidade atendida
	column 'Cidade'
		dataType: string
		lineageTag: f51b7fb2-e15f-4d26-9b85-d847446e4203
		summarizeBy: none
		sourceColumn: Cidade
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	/// Unidade federativa
	column 'UF'
		dataType: string
		lineageTag: 45752515-0eea-40db-8ef6-1dac8338b78d
		summarizeBy: none
		sourceColumn: UF
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	/// Região do país
	column 'Regiao'
		dataType: string
		lineageTag: 49373a9c-b65c-4bd7-b258-15e3acdb19b9
		summarizeBy: none
		sourceColumn: Regiao

		annotation SummarizationSetBy = Automatic

	/// Latitude do aeroporto
	column 'Latitude'
		dataType: double
		lineageTag: 3aff5279-0772-424a-8ad2-2d1fcdc9c035
		summarizeBy: none
		sourceColumn: Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	/// Longitude do aeroporto
	column 'Longitude'
		dataType: double
		lineageTag: 07234435-947b-4f3a-a48f-6c358ba6ece4
		summarizeBy: none
		sourceColumn: Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	partition dAeroporto = m
		mode: import
		queryGroup: Dimensoes
		source =
				let
				    // Une os aeroportos que aparecem como origem e como destino, para a dimensão
				    // cobrir toda a malha e não apenas as partidas.
				    Orig = Table.RenameColumns(
				        Table.SelectColumns( Fonte, {"origem_iata","origem_cidade","origem_uf","origem_regiao","origem_lat","origem_lon"} ),
				        {{"origem_iata","IATA"},{"origem_cidade","Cidade"},{"origem_uf","UF"},
				         {"origem_regiao","Regiao"},{"origem_lat","Latitude"},{"origem_lon","Longitude"}} ),
				    Dest = Table.RenameColumns(
				        Table.SelectColumns( Fonte, {"destino_iata","destino_cidade","destino_uf","destino_regiao","destino_lat","destino_lon"} ),
				        {{"destino_iata","IATA"},{"destino_cidade","Cidade"},{"destino_uf","UF"},
				         {"destino_regiao","Regiao"},{"destino_lat","Latitude"},{"destino_lon","Longitude"}} ),
				    Tudo = Table.Combine( {Orig, Dest} ),
				    Unicos = Table.Distinct( Tudo, {"IATA"} ),
				    ComRotulo = Table.AddColumn( Unicos, "Aeroporto", each [Cidade] & " (" & [IATA] & ")", type text ),
				    Ordenado = Table.Sort( ComRotulo, {{"Aeroporto", Order.Ascending}} )
				in
				    Ordenado

	annotation PBI_ResultType = Table
