/// Tabela fato: um registro por voo realizado ou cancelado.
table fVoos
	lineageTag: 1415eea7-964d-448e-a531-ccc43bc8dd52

	/// Identificador unico do voo
	column id_voo
		dataType: string
		lineageTag: 1b7b90da-dfac-4b5f-88e8-3ae382b2af08
		summarizeBy: none
		sourceColumn: id_voo

		annotation SummarizationSetBy = Automatic

	/// Numero comercial do voo
	column numero_voo
		dataType: string
		lineageTag: 50938a21-710a-46cb-9e2f-55fe7e06f4cd
		summarizeBy: none
		sourceColumn: numero_voo

		annotation SummarizationSetBy = Automatic

	/// Data de realizacao do voo
	column data_voo
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4209f6c3-78bf-47c9-b15e-269d43a59ac6
		summarizeBy: none
		sourceColumn: data_voo
		variation Variacao
			isDefault
			relationship: rel_calendario_voos
			defaultHierarchy: dCalendario.'Hierarquia de Datas'


		annotation SummarizationSetBy = Automatic

	/// Ano do voo
	column ano
		dataType: int64
		formatString: 0
		lineageTag: 65df6724-77c1-4f31-ad39-efb73fa9efeb
		summarizeBy: none
		sourceColumn: ano

		annotation SummarizationSetBy = Automatic

	/// Numero do mes (1-12)
	column mes
		dataType: int64
		formatString: 0
		lineageTag: a6a1f48f-5c01-4015-95c4-9a635446133f
		summarizeBy: none
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	/// Nome do mes por extenso
	column mes_nome
		dataType: string
		lineageTag: 515b4488-cc4a-4725-8015-ca97e3d0862c
		summarizeBy: none
		sourceColumn: mes_nome

		annotation SummarizationSetBy = Automatic

	/// Competencia no formato AAAA-MM
	column ano_mes
		dataType: string
		lineageTag: 896aa2d7-4889-4a62-99b1-a245bb35de2d
		summarizeBy: none
		sourceColumn: ano_mes

		annotation SummarizationSetBy = Automatic

	/// Dia da semana do voo
	column dia_semana
		dataType: string
		lineageTag: dcaa44bf-1fbd-4406-954a-1bc12fa3675b
		summarizeBy: none
		sourceColumn: dia_semana

		annotation SummarizationSetBy = Automatic

	/// Cidade do aeroporto de origem
	column origem_cidade
		dataType: string
		lineageTag: ea371a89-81af-42a8-b77b-c1eabbe56ef6
		summarizeBy: none
		sourceColumn: origem_cidade
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	/// Codigo IATA do aeroporto de origem
	column origem_iata
		dataType: string
		lineageTag: 6bbc9231-c022-4cc5-9196-de9fae55cb71
		summarizeBy: none
		sourceColumn: origem_iata

		annotation SummarizationSetBy = Automatic

	/// UF do aeroporto de origem
	column origem_uf
		dataType: string
		lineageTag: 55c9d64d-b4fd-4500-865f-6bf42c70d318
		summarizeBy: none
		sourceColumn: origem_uf
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	/// Regiao do aeroporto de origem
	column origem_regiao
		dataType: string
		lineageTag: 7dcdf9b9-c6db-40fc-a305-37ba424541bb
		summarizeBy: none
		sourceColumn: origem_regiao

		annotation SummarizationSetBy = Automatic

	/// Latitude do aeroporto de origem
	column origem_lat
		dataType: double
		lineageTag: 7a30ecd0-7ffd-4d6a-8142-bd8467373c1b
		summarizeBy: none
		sourceColumn: origem_lat
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	/// Longitude do aeroporto de origem
	column origem_lon
		dataType: double
		lineageTag: 98083cf4-3c83-44a3-aedd-b6e9b3145f30
		summarizeBy: none
		sourceColumn: origem_lon
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	/// Cidade do aeroporto de destino
	column destino_cidade
		dataType: string
		lineageTag: 451d8569-5810-4b2b-b241-f852d7ff661f
		summarizeBy: none
		sourceColumn: destino_cidade
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	/// Codigo IATA do aeroporto de destino
	column destino_iata
		dataType: string
		lineageTag: e6e088e8-0b01-4b9c-b74a-95c184f47858
		summarizeBy: none
		sourceColumn: destino_iata

		annotation SummarizationSetBy = Automatic

	/// UF do aeroporto de destino
	column destino_uf
		dataType: string
		lineageTag: 2b4db909-647b-4324-874b-2a4b39d8150a
		summarizeBy: none
		sourceColumn: destino_uf
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	/// Regiao do aeroporto de destino
	column destino_regiao
		dataType: string
		lineageTag: aee9a69c-961a-4311-881c-da25fdea7774
		summarizeBy: none
		sourceColumn: destino_regiao

		annotation SummarizationSetBy = Automatic

	/// Latitude do aeroporto de destino
	column destino_lat
		dataType: double
		lineageTag: af56e862-ca53-49ec-818f-b17170ed0034
		summarizeBy: none
		sourceColumn: destino_lat
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	/// Longitude do aeroporto de destino
	column destino_lon
		dataType: double
		lineageTag: 6d412f12-60a0-4ce9-9abf-b24194cf77bd
		summarizeBy: none
		sourceColumn: destino_lon
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	/// Par origem-destino (ex.: GRU - SDU)
	column rota
		dataType: string
		lineageTag: 81e8767d-8e56-4db3-b722-98fff1cbac0e
		summarizeBy: none
		sourceColumn: rota

		annotation SummarizationSetBy = Automatic

	/// Distancia da rota em quilometros
	column distancia_km
		dataType: int64
		formatString: #,0
		lineageTag: 7748cdbf-730a-4dff-8422-e96f378a6188
		summarizeBy: none
		sourceColumn: distancia_km

		annotation SummarizationSetBy = Automatic

	/// Modelo da aeronave utilizada
	column tipo_aeronave
		dataType: string
		lineageTag: f7eb3a2b-dacb-41f1-bbcd-0b81e43606c6
		summarizeBy: none
		sourceColumn: tipo_aeronave

		annotation SummarizationSetBy = Automatic

	/// Assentos disponiveis na aeronave
	column capacidade_aeronave
		dataType: int64
		formatString: #,0
		lineageTag: 842ecb93-1be3-4677-8c13-0ddbbe7753bf
		summarizeBy: none
		sourceColumn: capacidade_aeronave

		annotation SummarizationSetBy = Automatic

	/// Passageiros transportados no voo
	column passageiros
		dataType: int64
		formatString: #,0
		lineageTag: 4326f39b-be7d-4242-a01d-5f0a0559d309
		summarizeBy: none
		sourceColumn: passageiros

		annotation SummarizationSetBy = Automatic

	/// Passageiros dividido pela capacidade
	column taxa_ocupacao
		dataType: double
		formatString: 0.0%
		lineageTag: 54219734-eda7-4f89-93f3-42841161d4c3
		summarizeBy: none
		sourceColumn: taxa_ocupacao

		annotation SummarizationSetBy = Automatic

	/// Preco medio pago por passageiro
	column preco_medio_passagem
		dataType: double
		formatString: "R$" #,0.00
		lineageTag: 2857be4c-daaa-4071-b0f6-e535d1e44af4
		summarizeBy: none
		sourceColumn: preco_medio_passagem

		annotation SummarizationSetBy = Automatic

	/// Receita bruta gerada pelo voo
	column receita_voo
		dataType: double
		formatString: "R$" #,0.00
		lineageTag: 38a12745-c0eb-4e84-9a82-9f1ed7b7b5ce
		summarizeBy: none
		sourceColumn: receita_voo

		annotation SummarizationSetBy = Automatic

	/// Custo operacional total do voo
	column custo_voo
		dataType: double
		formatString: "R$" #,0.00
		lineageTag: a1454ba6-e21b-42a5-b1ef-0a9ede5b5ded
		summarizeBy: none
		sourceColumn: custo_voo

		annotation SummarizationSetBy = Automatic

	/// Receita menos custo do voo
	column lucro_voo
		dataType: double
		formatString: "R$" #,0.00
		lineageTag: 1b954a18-f09a-4ead-9b0e-4f29e202c4bb
		summarizeBy: none
		sourceColumn: lucro_voo

		annotation SummarizationSetBy = Automatic

	/// Minutos de atraso na decolagem
	column atraso_minutos
		dataType: double
		formatString: #,0
		lineageTag: 6eec5e14-f1c3-4c52-96e4-f27ef46d45a7
		summarizeBy: none
		sourceColumn: atraso_minutos

		annotation SummarizationSetBy = Automatic

	/// Pontual, Atrasado ou Cancelado
	column situacao_voo
		dataType: string
		lineageTag: 4204dcc9-3fee-4acc-ae61-d23de3f954f5
		summarizeBy: none
		sourceColumn: situacao_voo

		annotation SummarizationSetBy = Automatic

	/// Causa registrada do atraso ou cancelamento
	column motivo_atraso_cancelamento
		dataType: string
		lineageTag: 30390255-7157-40ae-ba5c-688d4c009ed8
		summarizeBy: none
		sourceColumn: motivo_atraso_cancelamento

		annotation SummarizationSetBy = Automatic

	/// Tempo de voo em minutos
	column duracao_minutos
		dataType: int64
		formatString: #,0
		lineageTag: 50eeb9e0-a621-4dd8-a676-51f9a5e20dac
		summarizeBy: none
		sourceColumn: duracao_minutos

		annotation SummarizationSetBy = Automatic

	/// Nota media de satisfacao (1 a 5)
	column satisfacao_passageiros
		dataType: double
		formatString: 0.0
		lineageTag: c351ca5f-c642-427a-ab36-d0554de51cc4
		summarizeBy: none
		sourceColumn: satisfacao_passageiros

		annotation SummarizationSetBy = Automatic

	/// Faixa de atraso agrupada em intervalos, usada no histograma de atrasos.
	column 'Faixa de Atraso' =
			VAR a = fVoos[atraso_minutos]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK( a ),                 "Cancelado",
			        a <= 15,                      "0-15 min (pontual)",
			        a <= 30,                      "16-30 min",
			        a <= 60,                      "31-60 min",
			        a <= 120,                     "61-120 min",
			        "Acima de 120 min"
			    )
		dataType: string
		lineageTag: 70d1894d-a533-4d2d-a93a-a041105fbbd0
		summarizeBy: none
		sortByColumn: 'Ordem Faixa Atraso'

		annotation SummarizationSetBy = Automatic

	/// Coluna auxiliar que ordena as faixas de atraso no eixo do grafico.
	column 'Ordem Faixa Atraso' =
			VAR a = fVoos[atraso_minutos]
			RETURN
			    SWITCH( TRUE(),
			        ISBLANK( a ), 0,
			        a <= 15,  1,
			        a <= 30,  2,
			        a <= 60,  3,
			        a <= 120, 4,
			        5
			    )
		dataType: int64
		formatString: 0
		lineageTag: 7e80b620-f58f-4c37-a0ca-d332cc3962b7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Classifica o voo entre lucrativo e deficitario para analise de rentabilidade.
	column 'Resultado do Voo' =
			IF( fVoos[situacao_voo] = "Cancelado", "Cancelado", IF( fVoos[lucro_voo] >= 0, "Lucrativo", "Deficitario" ) )
		dataType: string
		lineageTag: f5adff09-f97c-4b66-b483-85502708a830
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Agrupa a taxa de ocupacao em faixas para analise de rentabilidade por lotacao.
	column 'Faixa de Ocupacao' =
			VAR o = fVoos[taxa_ocupacao]
			RETURN
			    SWITCH( TRUE(),
			        fVoos[situacao_voo] = "Cancelado", "Cancelado",
			        o < 0.6,  "Abaixo de 60%",
			        o < 0.75, "60% a 75%",
			        o < 0.9,  "75% a 90%",
			        "Acima de 90%"
			    )
		dataType: string
		lineageTag: 04f29b92-f5a0-422a-bce4-864241b3becb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Mantem o nome das 15 rotas com mais passageiros e agrupa as demais, para deixar o ranking legivel.
	column 'Rota Top 15' =
			VAR _pos =
			    RANKX(
			        ALL( fVoos[rota] ),
			        CALCULATE( SUM( fVoos[passageiros] ), ALLEXCEPT( fVoos, fVoos[rota] ) ),
			        ,
			        DESC,
			        DENSE
			    )
			RETURN
			    IF( _pos <= 15, fVoos[rota], "Demais rotas" )
		dataType: string
		lineageTag: ec06a09a-41b6-4afd-957c-2eb9eeaa7544
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Rotulo do aeroporto de origem no formato Cidade (IATA).
	column 'Aeroporto de Origem' =
			fVoos[origem_cidade] & " (" & fVoos[origem_iata] & ")"
		dataType: string
		lineageTag: 34d0df32-4b46-42ab-8bde-32474f0cc4df
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Agrupa as rotas por extensao, usada na analise de preco por distancia.
	column 'Faixa de Distancia' =
			VAR d = fVoos[distancia_km]
			RETURN
			    SWITCH( TRUE(),
			        d < 500,  "Curta (ate 500 km)",
			        d < 1500, "Media (500 a 1.500 km)",
			        d < 2500, "Longa (1.500 a 2.500 km)",
			        "Muito longa (acima de 2.500 km)"
			    )
		dataType: string
		lineageTag: 37d67c05-aae0-4a3c-a9f2-72b1f0d9ed85
		summarizeBy: none
		sortByColumn: 'Ordem Faixa Distancia'

		annotation SummarizationSetBy = Automatic

	/// Coluna auxiliar de ordenacao das faixas de distancia.
	column 'Ordem Faixa Distancia' =
			SWITCH( TRUE(), fVoos[distancia_km] < 500, 1, fVoos[distancia_km] < 1500, 2, fVoos[distancia_km] < 2500, 3, 4 )
		dataType: int64
		formatString: 0
		lineageTag: d24acce3-b565-4744-bfaa-aa39d2c0b43b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Mantem o nome das 15 rotas com maior atraso medio (entre as que tem ao menos 10 voos) e agrupa as demais.
	column 'Rota Top Atraso' =
			VAR _voosRota =
			    CALCULATE( COUNTROWS( fVoos ), ALLEXCEPT( fVoos, fVoos[rota] ) )
			VAR _relevantes =
			    FILTER(
			        ALL( fVoos[rota] ),
			        CALCULATE( COUNTROWS( fVoos ), ALLEXCEPT( fVoos, fVoos[rota] ) ) >= 10
			    )
			VAR _pos =
			    RANKX(
			        _relevantes,
			        CALCULATE( AVERAGE( fVoos[atraso_minutos] ), ALLEXCEPT( fVoos, fVoos[rota] ) ),
			        ,
			        DESC,
			        DENSE
			    )
			RETURN
			    IF( _voosRota >= 10 && _pos <= 15, fVoos[rota], "Demais rotas" )
		dataType: string
		lineageTag: 5b042dbf-a96b-46e0-9773-73b2213a1ab7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fVoos = m
		mode: import
		queryGroup: Fato
		source =
				let
				    // Le o CSV publicado no OneDrive corporativo / SharePoint.
				    // A autenticacao e feita com a Conta Organizacional, sem necessidade de gateway.
				    Pasta = SharePoint.Files( pUrlOneDrive, [ApiVersion = 15] ),
				    Arquivo = Table.SelectRows( Pasta, each Text.Lower( [Name] ) = Text.Lower( pNomeArquivo ) ),
				    Conteudo =
				        if Table.IsEmpty( Arquivo )
				        then error "Arquivo '" & pNomeArquivo & "' nao encontrado em " & pUrlOneDrive
				        else Arquivo{0}[Content],
				    Origem = Csv.Document(
				        Conteudo,
				        [Delimiter = ",", Columns = 35, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Cabecalho = Table.PromoteHeaders( Origem, [PromoteAllScalars = true] ),
				    Tipos = Table.TransformColumnTypes(
				        Cabecalho,
				        {{"id_voo", type text}, {"numero_voo", type text}, {"data_voo", type date}, {"ano", Int64.Type}, {"mes", Int64.Type}, {"mes_nome", type text}, {"ano_mes", type text}, {"dia_semana", type text}, {"origem_cidade", type text}, {"origem_iata", type text}, {"origem_uf", type text}, {"origem_regiao", type text}, {"origem_lat", type number}, {"origem_lon", type number}, {"destino_cidade", type text}, {"destino_iata", type text}, {"destino_uf", type text}, {"destino_regiao", type text}, {"destino_lat", type number}, {"destino_lon", type number}, {"rota", type text}, {"distancia_km", Int64.Type}, {"tipo_aeronave", type text}, {"capacidade_aeronave", Int64.Type}, {"passageiros", Int64.Type}, {"taxa_ocupacao", type number}, {"preco_medio_passagem", type number}, {"receita_voo", type number}, {"custo_voo", type number}, {"lucro_voo", type number}, {"atraso_minutos", type number}, {"situacao_voo", type text}, {"motivo_atraso_cancelamento", type text}, {"duracao_minutos", Int64.Type}, {"satisfacao_passageiros", type number}},
				        "en-US"
				    ),
				    SemLinhasVazias = Table.SelectRows( Tipos, each [id_voo] <> null and [id_voo] <> "" )
				in
				    SemLinhasVazias

	annotation PBI_ResultType = Table
